TARGETS=main.cpp vec.hpp pallete.hpp iterable_queue.hpp player.hpp common.hpp gameobject.hpp
FRAMEWORK=../cursesgame.hpp ../game.hpp

a.out: $(TARGETS) $(FRAMEWORK)
	g++ -I/usr/include/lua5.3 main.cpp -lncurses -llua5.3