
roam.register_on_tick(function ()
    file = io.open("log", "a")
    io.output(file)
    --io.write("RVRVTRBRBRBTB\n")
    local player = roam.player.fetch()
    --io.write(string.format("pos: %s\n", player:getpos()))
    io.write(string.format("player: %s\n", player))
    player:setpos({x = player:getpos().x + 1})
    io.write(string.format("PLA: %s\n", player))
    io.close(file)
end)